version: "3.7"
services:

  # application service
  app:
    container_name: "flask_app"
    image: flask_app
    environment:
      - CONTAINERENV=True
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5000:5000"
    restart: always
    networks:
      - main
    depends_on:
      - db

  # database service
  db:
    container_name: "redis"
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - main


networks:
  main:
    driver: bridge